<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterBudgetSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Bersihkan tabel master_budget terlebih dahulu sebelum diisi
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('master_budget')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // 2. Kumpulan Data 100% Lengkap dari File Excel Project 38 (FIXED)
        $project38 = [
            ['kode_project' => '38', 'kode_budget' => '1.1', 'nama_budget' => 'Component 1: Optimizing Posyandu Services with a human life cycle approach and friendly service'],
            ['kode_project' => '38', 'kode_budget' => '1.1.1', 'nama_budget' => 'Posyandu Services with a human life cycle approach'],
            ['kode_project' => '38', 'kode_budget' => '1.1.1.1', 'nama_budget' => 'Workshop on Introduction to Posyandu Service applying Human Life Cycle Approach at the Regency level'],
            ['kode_project' => '38', 'kode_budget' => '1.1.1.2', 'nama_budget' => 'Socialization on Implementing Plan of Posyandu Service applying Human Life Cycle Approach in the Village'],
            ['kode_project' => '38', 'kode_budget' => '1.1.2', 'nama_budget' => 'Implementing Posyandu Service using Human Life Cycle Approach'],
            ['kode_project' => '38', 'kode_budget' => '1.1.2.1', 'nama_budget' => 'Training on Posyandu Service using Human Life Cycle Approach'],
            ['kode_project' => '38', 'kode_budget' => '1.1.2.2', 'nama_budget' => 'Supporting adequate needed Posyandu tools according to Ministry of Health standards'],
            ['kode_project' => '38', 'kode_budget' => '1.1.2.3', 'nama_budget' => 'Socialization on Healthy and Hygiene Behavior Lifestyle in PAUD and Elementary School'],
            ['kode_project' => '38', 'kode_budget' => '1.1.2.4', 'nama_budget' => 'Inter-Posyandu Service Quality Contest'],
            ['kode_project' => '38', 'kode_budget' => '1.1.2.5', 'nama_budget' => 'Information, Education Communication (IEC) Media Equipment'],
            ['kode_project' => '38', 'kode_budget' => '1.1.3', 'nama_budget' => 'Capacity Building for Posyandu Cadres'],
            ['kode_project' => '38', 'kode_budget' => '1.1.3.1', 'nama_budget' => 'Interpersonal Communication Training for counseling on balanced nutritional diet and reproductive health'],
            ['kode_project' => '38', 'kode_budget' => '1.1.3.2', 'nama_budget' => 'Infant and Child Feeding Training applying concept of local food usage'],
            ['kode_project' => '38', 'kode_budget' => '1.1.3.3', 'nama_budget' => 'Education on Parenting Patterns and Providing Healthy Nutrition for Families with babies, children under 5 years old, and pregnant women'],
            ['kode_project' => '38', 'kode_budget' => '1.1.3.4', 'nama_budget' => 'Class for Pregnant Women and Suami Siaga (Husbands on Alert)'],
            ['kode_project' => '38', 'kode_budget' => '1.1.4', 'nama_budget' => 'Village Information System'],
            ['kode_project' => '38', 'kode_budget' => '1.1.4.1', 'nama_budget' => 'Village Health Data Assessment'],
            ['kode_project' => '38', 'kode_budget' => '1.1.4.2', 'nama_budget' => 'Workshop on Preparing Village Health Information System Involving Multistakeholders at the Regency Level'],
            ['kode_project' => '38', 'kode_budget' => '1.1.4.3', 'nama_budget' => 'Expert Consultancy related to Health Data Entry on SID'],
            ['kode_project' => '38', 'kode_budget' => '1.1.4.4', 'nama_budget' => 'Training on Health Data Entry in Village Information Systems (SID)'],
            ['kode_project' => '38', 'kode_budget' => '1.1.4.5', 'nama_budget' => 'Supporting facilities for piloting the Village Health Information System'],
            ['kode_project' => '38', 'kode_budget' => '1.1.4.6', 'nama_budget' => 'Monitoring on Health Data Entry in the Village Information System'],
            ['kode_project' => '38', 'kode_budget' => '1.2', 'nama_budget' => 'Component 2: Engaging Community and FBO Participation to Promote Family Health and Prevent Violence against Women and Children'],
            ['kode_project' => '38', 'kode_budget' => '1.2.1', 'nama_budget' => 'Participatory Reflection and Action (PRA) and SALT approach'],
            ['kode_project' => '38', 'kode_budget' => '1.2.1.1', 'nama_budget' => 'PRA and SALT training'],
            ['kode_project' => '38', 'kode_budget' => '1.2.1.2', 'nama_budget' => 'PRA and SALT Appreciative Visit to communities'],
            ['kode_project' => '38', 'kode_budget' => '1.2.1.2.1', 'nama_budget' => 'PRA Visit'],
            ['kode_project' => '38', 'kode_budget' => '1.2.1.2.2', 'nama_budget' => 'SALT Visit'],
            ['kode_project' => '38', 'kode_budget' => '1.2.1.3', 'nama_budget' => 'Workshop on Preparing Action Plans based on SALT visit and PRA result'],
            ['kode_project' => '38', 'kode_budget' => '1.2.2', 'nama_budget' => 'Integration of Village Health Action Plan in Village Budgeting'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3', 'nama_budget' => 'Action Plan Implementation on Family and Church Community Health Initiatives'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.1', 'nama_budget' => 'Capacity Building on Family and Church Community Initiatives'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.1.1', 'nama_budget' => 'Training on Primary Health in Families and Church Communities'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.1.2', 'nama_budget' => 'Training on Traditional Health for Families and Church Communities'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.1.2.1', 'nama_budget' => 'Training Traditional Health Families & Church (Village level)'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.1.2.2', 'nama_budget' => 'Training Traditional Health Families & Church (Targeted Church)'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.1.3', 'nama_budget' => 'Training on Food Security, Utilization and Processing of Local Food for Families'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.1.4', 'nama_budget' => 'Supporting Initiatives and Social Support'],
            ['kode_project' => '38', 'kode_budget' => '1.2.3.2', 'nama_budget' => 'Technical Assistance on Village Law for budgeting health initiative'],
            ['kode_project' => '38', 'kode_budget' => '1.2.4', 'nama_budget' => 'Action Plan Implementation on Gender, Reproductive Health and Prevention of Violence against Women and Children (KTPA)'],
            ['kode_project' => '38', 'kode_budget' => '1.2.4.1', 'nama_budget' => 'Education on Gender, Reproductive Health and KTPA/Violence Prevention'],
            ['kode_project' => '38', 'kode_budget' => '1.2.4.1.1', 'nama_budget' => 'Education Reproductive Health & KTPA/Violence Prevention (Village level)'],
            ['kode_project' => '38', 'kode_budget' => '1.2.4.1.2', 'nama_budget' => 'Education Reproductive Health & KTPA/Violence Prevention (Targeted Church)'],
            
            // BARIS 44 YANG SUDAH BERHASIL DI-FIX OLEH GEMINI
            ['kode_project' => '38', 'kode_budget' => '1.2.4.2', 'nama_budget' => 'Supporting and Strengthening Community-Based Protection Group for Women and Children (LBK/WPA/PATBM)'],
            
            ['kode_project' => '38', 'kode_budget' => '1.2.4.2.1', 'nama_budget' => 'Implementation of Violence against Women & Children Program in Alor'],
            ['kode_project' => '38', 'kode_budget' => '1.2.4.2.2', 'nama_budget' => 'Implementation of Violence against Women & Children Program in Malaka'],
            ['kode_project' => '38', 'kode_budget' => '1.3', 'nama_budget' => 'Component 3: Effective Project Management, Monitoring, and Evaluation'],
            ['kode_project' => '38', 'kode_budget' => '1.3.1', 'nama_budget' => 'Project Monitoring, Evaluation and Knowledge Management'],
            ['kode_project' => '38', 'kode_budget' => '1.3.1.1', 'nama_budget' => 'National Seminar Lessons Learned of Implementing Posyandu'],
            ['kode_project' => '38', 'kode_budget' => '1.3.1.2', 'nama_budget' => 'Annual Report'],
            ['kode_project' => '38', 'kode_budget' => '1.3.1.3', 'nama_budget' => 'Mini Library Development (media knowledge management)'],
            ['kode_project' => '38', 'kode_budget' => '1.3.1.4', 'nama_budget' => 'Internal Monitoring Evaluation'],
            ['kode_project' => '38', 'kode_budget' => '1.3.2', 'nama_budget' => 'Project Supervision and Mentoring'],
            ['kode_project' => '38', 'kode_budget' => '1.3.2.1', 'nama_budget' => 'Supervision Project Management and Director of CD Bethesda'],
            ['kode_project' => '38', 'kode_budget' => '1.3.2.2', 'nama_budget' => 'Supervision Area Manager'],
            ['kode_project' => '38', 'kode_budget' => '1.3.2.3', 'nama_budget' => 'Supervision Local staffs'],
            ['kode_project' => '38', 'kode_budget' => '1.3.3', 'nama_budget' => 'Coordination Meeting in area of work and headquarter and Strategic Planning Workshop'],
            ['kode_project' => '38', 'kode_budget' => '1.3.3.1', 'nama_budget' => 'field offices'],
            ['kode_project' => '38', 'kode_budget' => '1.3.3.2', 'nama_budget' => 'Headquarter'],
            ['kode_project' => '38', 'kode_budget' => '1.3.3.3', 'nama_budget' => 'Strategic Planning Workshop'],
            ['kode_project' => '38', 'kode_budget' => '1.4', 'nama_budget' => 'Capacity Building for Staffs'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1', 'nama_budget' => 'Training of Fasilitator'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1.1', 'nama_budget' => 'Training on Policy about Implementing Posyandu applying Life Cycle Approach'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1.2', 'nama_budget' => 'Training on Counseling Methods for Balanced Nutritional Diet and Reproductive Health'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1.3', 'nama_budget' => 'Training on feeding babies and children based on local food'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1.4', 'nama_budget' => 'Training on Herbal Medicine Making for preventive and promotive purposes'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1.5', 'nama_budget' => 'Training on Village Information System'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1.6', 'nama_budget' => 'Training on Local Food Security and Garden Management (organic fertilizer making, vegetables and fruit plantation management)'],
            ['kode_project' => '38', 'kode_budget' => '1.4.1.7', 'nama_budget' => 'Training on Gender, Reproductive and Sexual Health, and Prevention of Violence against Women and Children.'],
            ['kode_project' => '38', 'kode_budget' => '1.4.2', 'nama_budget' => 'Workshop on Outcome Impact Oriented (Impact Chain) and Monitoring'],
            ['kode_project' => '38', 'kode_budget' => '1.4.3', 'nama_budget' => 'Workshop on Program Management and Institutional SOPs'],
            ['kode_project' => '38', 'kode_budget' => '1.4.4', 'nama_budget' => 'Networking'],
            ['kode_project' => '38', 'kode_budget' => '2.0', 'nama_budget' => 'Personnel'],
            ['kode_project' => '38', 'kode_budget' => '2.1', 'nama_budget' => 'Program personnel'],
            ['kode_project' => '38', 'kode_budget' => '2.2', 'nama_budget' => 'Administration personnel'],
            ['kode_project' => '38', 'kode_budget' => '3.0', 'nama_budget' => 'Administration'],
            ['kode_project' => '38', 'kode_budget' => '3.1.1', 'nama_budget' => 'Office Rent'],
            ['kode_project' => '38', 'kode_budget' => '3.1.2', 'nama_budget' => 'Running Office Cost'],
            ['kode_project' => '38', 'kode_budget' => '3.1.2.1', 'nama_budget' => 'Office Material'],
            ['kode_project' => '38', 'kode_budget' => '3.1.2.2', 'nama_budget' => 'Listrik & air'],
            ['kode_project' => '38', 'kode_budget' => '3.1.2.3', 'nama_budget' => 'Communication, email and postal'],
            ['kode_project' => '38', 'kode_budget' => '3.1.2.4', 'nama_budget' => 'office equipment maintenance'],
            ['kode_project' => '38', 'kode_budget' => '3.1.2.5', 'nama_budget' => 'maintenance of office vehicles'],
            ['kode_project' => '38', 'kode_budget' => '3.1.2.6', 'nama_budget' => 'General Office maintenance'],
            ['kode_project' => '38', 'kode_budget' => '3.3', 'nama_budget' => 'Administration - Audit'],
            ['kode_project' => '38', 'kode_budget' => '4.0', 'nama_budget' => 'Procurement'],
            ['kode_project' => '38', 'kode_budget' => '4.1', 'nama_budget' => 'Car'],
            ['kode_project' => '38', 'kode_budget' => '4.2', 'nama_budget' => 'Laptop'],
            ['kode_project' => '38', 'kode_budget' => '4.3', 'nama_budget' => 'LCD Projector'],
            ['kode_project' => '38', 'kode_budget' => '4.4', 'nama_budget' => 'Smartphone for field office'],
            ['kode_project' => '38', 'kode_budget' => '4.5', 'nama_budget' => 'External Hardisk'],
            ['kode_project' => '38', 'kode_budget' => '4.6', 'nama_budget' => 'AC'],
            ['kode_project' => '38', 'kode_budget' => '6.0', 'nama_budget' => 'External Evaluation'],
            ['kode_project' => '38', 'kode_budget' => '7.0', 'nama_budget' => 'Reserve'],
        ];

        // 3. Kumpulan Data 100% Lengkap dari File Excel Project 40
        $project40 = [
            ['kode_project' => '40', 'kode_budget' => '1.0', 'nama_budget' => 'Project activities'],
            ['kode_project' => '40', 'kode_budget' => '1.1', 'nama_budget' => 'Komponen 1 Pengendalian HIV dan AIDS Secara Struktural'],
            ['kode_project' => '40', 'kode_budget' => '1.1.1', 'nama_budget' => 'Lobby dan koordinasi dengan pemangku kebijakan'],
            ['kode_project' => '40', 'kode_budget' => '1.1.1.1', 'nama_budget' => 'Nota kesepahaman dengan Walikota/Bupati'],
            ['kode_project' => '40', 'kode_budget' => '1.1.1.2', 'nama_budget' => 'Advokasi kebijakan anggaran untuk pengendalian HIV dan AIDS'],
            ['kode_project' => '40', 'kode_budget' => '1.1.1.3', 'nama_budget' => 'Advokasi Kebijakan Peningkatan Kualitas Layanan Kesehatan bagi ODHIV di Tingkat Provinsi dan Nasional'],
            ['kode_project' => '40', 'kode_budget' => '1.1.1.4', 'nama_budget' => 'Advokasi Anggaran Program HIV AIDS dan Integrasi WPA di tingkat Desa/Kelurahan'],
            ['kode_project' => '40', 'kode_budget' => '1.1.2', 'nama_budget' => 'FGD untuk memperkuat implementasi Rencana Aksi Daerah (RAD) Penanggulangan HIV dan AIDS'],
            ['kode_project' => '40', 'kode_budget' => '1.1.3', 'nama_budget' => 'Pertemuan Lintas Sektor Upaya Pengendalian HIV dan AIDS Berbasis Komunitas'],
            ['kode_project' => '40', 'kode_budget' => '1.1.4', 'nama_budget' => 'Networking'],
            ['kode_project' => '40', 'kode_budget' => '1.1.4.1', 'nama_budget' => 'Provinsi'],
            ['kode_project' => '40', 'kode_budget' => '1.1.4.2', 'nama_budget' => 'Nasional'],
            ['kode_project' => '40', 'kode_budget' => '1.1.4.3', 'nama_budget' => 'Internasional'],
            ['kode_project' => '40', 'kode_budget' => '1.2', 'nama_budget' => 'Komponen 2 Pengendalian HIV dan AIDS Secara Bio-medical'],
            ['kode_project' => '40', 'kode_budget' => '1.2.1', 'nama_budget' => 'Pelayanan VCT Mobile dan Pemeriksaan serta pengobatan IMS (Infeksi Menular Seksual)'],
            ['kode_project' => '40', 'kode_budget' => '1.2.1.1', 'nama_budget' => 'VCT Mobile'],
            ['kode_project' => '40', 'kode_budget' => '1.2.1.2', 'nama_budget' => 'Pemeriksaan serta pengobatan IMS (Infeksi Menular Seksual)'],
            ['kode_project' => '40', 'kode_budget' => '1.2.2', 'nama_budget' => 'Workshop Layanan Komprehensif Berkesinambungan HIV-IMS dan Sistem Rujukan untuk Layanan ARV'],
            ['kode_project' => '40', 'kode_budget' => '1.2.3', 'nama_budget' => 'Monitoring Implementasi MoU Pengendalian HIV di Perbatasan RI - Timor Leste'],
            ['kode_project' => '40', 'kode_budget' => '1.2.4', 'nama_budget' => 'Peningkatan kapasitas bagi nakes puskesmas / Rumah Sakit rujukan ARV'],
            ['kode_project' => '40', 'kode_budget' => '1.2.4.1', 'nama_budget' => 'Pelatihan Layanan Kesehatan HIV yang Ramah, Komprehensif Tanpa Stigma dan Diskriminasi Berbasis Gender dan Disabilitas'],
            ['kode_project' => '40', 'kode_budget' => '1.2.4.2', 'nama_budget' => 'Koordinasi Persiapan Layanan PDP Dinkes Kab Belu'],
            ['kode_project' => '40', 'kode_budget' => '1.2.4.3', 'nama_budget' => 'Fasilitasi magang (OJT) nakes pusk/RS untuk layanan PDP baru'],
            ['kode_project' => '40', 'kode_budget' => '1.2.4.4', 'nama_budget' => 'Supervisi dan Monitoring Layanan PDP di Kabupaten Belu'],
            ['kode_project' => '40', 'kode_budget' => '1.2.5', 'nama_budget' => 'Dukungan psikososial, peningkatan kapasitas & kualitashidup bagi ODHIV dan OHIDHA'],
            ['kode_project' => '40', 'kode_budget' => '1.2.5.1', 'nama_budget' => 'Pendidikan kesadaran (coaching-mentoring) & pendampingan psikososial bagi ODHIV/OHIDHA Baru & LFU'],
            ['kode_project' => '40', 'kode_budget' => '1.2.5.2', 'nama_budget' => 'Pemberdayaan ODHIV Melalui Peningkatan Keterampilan Hidup Berbasis Pangan Lokal dan Tradisional'],
            ['kode_project' => '40', 'kode_budget' => '1.2.5.2.1', 'nama_budget' => 'Pelatihan Pengolahan Pangan Lokal untuk Peningkatan Gizi ODHIV'],
            ['kode_project' => '40', 'kode_budget' => '1.2.5.2.2', 'nama_budget' => 'Pelatihan Pembuatan Ramuan Herbal Menjaga Stamina dan Mengatasi Efek Samping ARV'],
            ['kode_project' => '40', 'kode_budget' => '1.2.5.2.3', 'nama_budget' => 'Pelatihan Pijat Urut Tradisional untuk Mendukung Kesehatan ODHIV'],
            ['kode_project' => '40', 'kode_budget' => '1.2.5.3', 'nama_budget' => 'Training Penerimaan Diri dan Open Status bagi ODHIV'],
            ['kode_project' => '40', 'kode_budget' => '1.3', 'nama_budget' => 'Komponen 3 Pengendalian HIV dan AIDS Secara Sosio-ekonomi & Penguatan Komunitas'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1', 'nama_budget' => 'KIE HIV dan AIDS, Penjangkauan dan Kampanye Publik'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.1', 'nama_budget' => 'Kunjungan SALT dan Penjangkauan ODHIV LFU'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.1.1', 'nama_budget' => 'Kunjungan SALT bagi ODHIV, OHIDHA dan Kelompok Risiko Tinggi'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.1.2', 'nama_budget' => 'Workshop Hasil Kunjungan SALT'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.1.3', 'nama_budget' => 'Penjangkauan ODHIV LFU'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.2', 'nama_budget' => 'Pendidikan HIV Komunitas'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.2.1', 'nama_budget' => 'Pendidikan HIV komunitas umum, muda, agama (Kampung/Masjid/Gereja)'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.2.2', 'nama_budget' => 'Pendidikan HIV populasi kunci/berisiko (IRT, WPS, Ojek Belu)'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.2.3', 'nama_budget' => 'Pendidikan HIV komunitas pelajar & mahasiswa (MOS/Maba)'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.2.4', 'nama_budget' => 'Pendidikan HIV komunitas disabilitas'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.3', 'nama_budget' => 'Kampanye Publik'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.3.1', 'nama_budget' => 'Media promosi/kampanye tokoh agama/adat sebagai role model'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.3.2', 'nama_budget' => 'Kampanye melalui Media Sosial, Elektronik, Cetak dan Radio'],
            ['kode_project' => '40', 'kode_budget' => '1.3.1.3.3', 'nama_budget' => 'Peringatan Hari AIDS Sedunia (1 Desember)'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2', 'nama_budget' => 'Penguatan organisasi berbasis komunitas (WPA, KDS, & Transgender)'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.1', 'nama_budget' => 'Pelatihan HIV dan AIDS dan Pembentukan WPA'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.2', 'nama_budget' => 'Pelatihan SALT untuk ODHIV dan WPA'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.3', 'nama_budget' => 'Pelatihan Public Speaking & KAP bagi WPA dan KDS'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.4', 'nama_budget' => 'Pendampingan teknis pengelolaan program dan organisasi WPA & KDS'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.5', 'nama_budget' => 'Pelatihan Perencanaan Usaha Ekonomi Kreatif bagi WPA'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.6', 'nama_budget' => 'Supporting Usaha Ekonomi Kreatif bagi WPA'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.7', 'nama_budget' => 'Pelatihan manajemen organisasi, penguatan jaringan & advokasi KDS'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.8', 'nama_budget' => 'Dukungan sarana kesehatan ODHIV terlantar shelter Kebaya Yk'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.8.1', 'nama_budget' => 'Supporting sarana kesehatan ODHIV terlantar shelter Kebaya Yk'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.8.2', 'nama_budget' => 'Pemberian bantuan sarana kesehatan ODHIV terlantar shelter Kebaya Yk'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.9', 'nama_budget' => 'Pelatihan HIV, AIDS, dan Komunikasi Perubahan Perilaku Transgender'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.10', 'nama_budget' => 'Pendampingan Teknis Pengelolaan Program Yayasan Kebaya Yogyakarta'],
            ['kode_project' => '40', 'kode_budget' => '1.3.2.11', 'nama_budget' => 'Study Banding Komunitas Transgender Kaebeuk Belu ke Kebaya Yk'],
            ['kode_project' => '40', 'kode_budget' => '1.4', 'nama_budget' => 'Komponen 4 Manajemen Proyek, Pemantauan dan Evaluasi (PME)'],
            ['kode_project' => '40', 'kode_budget' => '1.4.1', 'nama_budget' => 'Pemantauan dan Evaluasi (PME) dan Knowledge Management'],
            ['kode_project' => '40', 'kode_budget' => '1.4.1.1', 'nama_budget' => 'PME - Evaluasi internal'],
            ['kode_project' => '40', 'kode_budget' => '1.4.1.2', 'nama_budget' => 'PME Knowledge Management'],
            ['kode_project' => '40', 'kode_budget' => '1.4.1.2.1', 'nama_budget' => 'PME Knowledge Management - Newsletter'],
            ['kode_project' => '40', 'kode_budget' => '1.4.1.2.2', 'nama_budget' => 'PME Knowledge Management - Annual Report'],
            ['kode_project' => '40', 'kode_budget' => '1.4.2', 'nama_budget' => 'Supervisi Teknis Program dan Manajemen Organisasi'],
            ['kode_project' => '40', 'kode_budget' => '1.4.2.1', 'nama_budget' => 'Supervisi Project Management, Tim Manajemen & Pengurus YAKKUM'],
            ['kode_project' => '40', 'kode_budget' => '1.4.2.2', 'nama_budget' => 'Supervisi Area Manager'],
            ['kode_project' => '40', 'kode_budget' => '1.4.2.3', 'nama_budget' => 'Supervisi Staf lokal'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3', 'nama_budget' => 'Pertemuan Koordinasi berkala & Workshop Rencana Strategis'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3.1', 'nama_budget' => 'Rapat koordinasi berkala'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3.1.1', 'nama_budget' => 'Rapat koordinasi Kantor Pusat'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3.1.2', 'nama_budget' => 'Rapat koordinasi Area'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3.2', 'nama_budget' => 'Workshop Rencana Strategis Mitra Strategis Berkelanjutan'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3.2.1', 'nama_budget' => 'Workshop Rencana Strategis di Kabupaten Belu'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3.2.2', 'nama_budget' => 'Workshop Rencana Strategis di Kota Yogyakarta'],
            ['kode_project' => '40', 'kode_budget' => '1.4.3.2.3', 'nama_budget' => 'Workshop Finalisasi Rencana Strategis'],
            ['kode_project' => '40', 'kode_budget' => '1.5', 'nama_budget' => 'Komponen 5 Peningkatan Kapasitas Staf (Capacity Building)'],
            ['kode_project' => '40', 'kode_budget' => '1.5.1', 'nama_budget' => 'ToF HIV and AIDS'],
            ['kode_project' => '40', 'kode_budget' => '1.5.2', 'nama_budget' => 'ToT Herbal untuk Mendukung Kesehatan ODHIV'],
            ['kode_project' => '40', 'kode_budget' => '1.5.3', 'nama_budget' => 'ToT Gizi untuk ODHIV berbasis Pangan Lokal'],
            ['kode_project' => '40', 'kode_budget' => '1.5.4', 'nama_budget' => 'Training of Trainer (ToT) Pijat Urut Tradisional untuk Mendukung Kesehatan ODHIV'],
            ['kode_project' => '40', 'kode_budget' => '1.5.5', 'nama_budget' => 'Training of Fasilitator (ToF) Teknik Fasilitasi, Pengorganisasian dan Advokasi'],
            ['kode_project' => '40', 'kode_budget' => '1.5.6', 'nama_budget' => 'Training of Trainer (ToT) SALT'],
            ['kode_project' => '40', 'kode_budget' => '1.5.7', 'nama_budget' => 'Training of Fasilitator Kesehatan Jiwa, dan Konseling Psikososial untuk Klien'],
            ['kode_project' => '40', 'kode_budget' => '1.5.8', 'nama_budget' => 'Training of Fasilitator Gender dan Inklusi Sosial'],
            ['kode_project' => '40', 'kode_budget' => '1.5.9', 'nama_budget' => 'Field Visit ke Yayasan Kebaya Yogyakarta'],
            ['kode_project' => '40', 'kode_budget' => '1.5.10', 'nama_budget' => 'Training Manajemen Program dan internalisasi nilai-nilai YAKKUM'],
            ['kode_project' => '40', 'kode_budget' => '2.0', 'nama_budget' => 'Personnel'],
            ['kode_project' => '40', 'kode_budget' => '2.1', 'nama_budget' => 'Programme personnel'],
            ['kode_project' => '40', 'kode_budget' => '2.1.1', 'nama_budget' => 'Program Coordinator'],
            ['kode_project' => '40', 'kode_budget' => '2.1.2', 'nama_budget' => 'Project Coordinator'],
            ['kode_project' => '40', 'kode_budget' => '2.1.3', 'nama_budget' => 'Community Organizer'],
            ['kode_project' => '40', 'kode_budget' => '2.1.4', 'nama_budget' => 'Area Coordinators'],
            ['kode_project' => '40', 'kode_budget' => '2.2', 'nama_budget' => 'Administration personnel'],
            ['kode_project' => '40', 'kode_budget' => '2.2.1', 'nama_budget' => 'Finance administrator'],
            ['kode_project' => '40', 'kode_budget' => '2.2.2', 'nama_budget' => 'Project Administrator'],
            ['kode_project' => '40', 'kode_budget' => '2.2.3', 'nama_budget' => 'Finance Assistant staff'],
            ['kode_project' => '40', 'kode_budget' => '2.2.4', 'nama_budget' => 'Minitoring Evaluation staff'],
            ['kode_project' => '40', 'kode_budget' => '2.2.5', 'nama_budget' => 'Database staff'],
            ['kode_project' => '40', 'kode_budget' => '3.0', 'nama_budget' => 'Administration'],
            ['kode_project' => '40', 'kode_budget' => '3.1', 'nama_budget' => 'Office Rent'],
            ['kode_project' => '40', 'kode_budget' => '3.2', 'nama_budget' => 'Running Office Cost'],
            ['kode_project' => '40', 'kode_budget' => '3.2.1', 'nama_budget' => 'Office Material'],
            ['kode_project' => '40', 'kode_budget' => '3.2.2', 'nama_budget' => 'Listrik & air'],
            ['kode_project' => '40', 'kode_budget' => '3.2.3', 'nama_budget' => 'Communication, email and postal'],
            ['kode_project' => '40', 'kode_budget' => '3.2.4', 'nama_budget' => 'office equipment maintenance'],
            ['kode_project' => '40', 'kode_budget' => '3.2.5', 'nama_budget' => 'maintenance of office vehicles'],
            ['kode_project' => '40', 'kode_budget' => '3.2.6', 'nama_budget' => 'General Office maintenance'],
            ['kode_project' => '40', 'kode_budget' => '3.3', 'nama_budget' => 'Audit'],
            ['kode_project' => '40', 'kode_budget' => '4.0', 'nama_budget' => 'Procurement'],
            ['kode_project' => '40', 'kode_budget' => '4.1', 'nama_budget' => 'Car'],
            ['kode_project' => '40', 'kode_budget' => '4.2', 'nama_budget' => 'Office Procurment'],
            ['kode_project' => '40', 'kode_budget' => '4.2.1', 'nama_budget' => 'Computers and Notebook'],
            ['kode_project' => '40', 'kode_budget' => '4.2.2', 'nama_budget' => 'AC'],
            ['kode_project' => '40', 'kode_budget' => '4.2.3', 'nama_budget' => 'Printer'],
            ['kode_project' => '40', 'kode_budget' => '4.2.4', 'nama_budget' => 'Hardisk'],
            ['kode_project' => '40', 'kode_budget' => '4.2.5', 'nama_budget' => 'Recorder'],
            ['kode_project' => '40', 'kode_budget' => '4.2.6', 'nama_budget' => 'Laser Pointer'],
            ['kode_project' => '40', 'kode_budget' => '6.1', 'nama_budget' => 'External evaluation'],
            ['kode_project' => '40', 'kode_budget' => '7.0', 'nama_budget' => 'Reserve'],
        ];

        // 4. Gabungkan dan masukkan semua data ke database dengan sistem chunk
        $allData = array_merge($project38, $project40);
        $chunks = array_chunk($allData, 50);
        
        foreach ($chunks as $chunk) {
            DB::table('master_budget')->insert($chunk);
        }
    }
}